#!/usr/bin/env bash

base_path=$0
if [ -L "$base_path" ]; then
    base_path=`readlink $base_path`
fi
base_path=`dirname $base_path`

pixie_path=`which pixie-vm`
if [ -z "$pixie_path" ]; then
    echo "Error: 'pixie-vm' must be on your PATH"
    exit 1
fi
run_dust="$pixie_path -l $base_path/src $base_path/run.pxi"

function load_path() {
    load_path=""
    if [ -f "project.pxi" ]; then
        load_path="`$run_dust load-path option`"
    fi
    echo $load_path
}

case $1 in
    ""|"repl")
        rlwrap_cmd=""
        if [ -n "`which rlwrap`" ]; then
            rlwrap_cmd="rlwrap -aignored -n"
        fi
        $rlwrap_cmd $pixie_path `load_path`
        ;;
    "run")
        shift
        file=$1
        shift
        $pixie_path `load_path` $file $@
        ;;
    -h|--help)
        $run_dust help
        ;;
    *)
        $run_dust $@
        ;;
esac
