#!/bin/bash

base_path=$(dirname `readlink -f $0`)
pixie_path=`which pixie-vm`
run_dust="$pixie_path -l $base_path/src $base_path/run.pxi"

function load_path() {
    load_path=""
    if [ -f "project.pxi" ]; then
        load_path="`$run_dust load-path option`"
    fi
    echo $load_path
}

case $1 in
    "get-deps")
        $run_dust $@ | sh
        ;;
    ""|"repl")
        rlwrap -a -n $pixie_path `load_path`
        ;;
    "run")
        shift
        file=$1
        shift
        $pixie_path `load_path` $file $@
        ;;
    -h|--help)
        $run_dust help
        ;;
    *)
        $run_dust $@
        ;;
esac
